version: '3.7'
services:
  rabbitmq:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: unpdf_mq
    restart: always
    ports:
      - 9890:15672
      - 8888:5672
    hostname: unpdf
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: unpdf
      RABBITMQ_DEFAULT_PASS: unpdf
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.05
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host

volumes:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge